apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - grafana-deployment.yaml
 # - loki-deployment.yaml
 # - alloy-daemonset.yaml

# Khai báo các Helm Chart cần tích hợp vào Kustomize
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.27.0               # Điền version chart bạn muốn dùng
    releaseName: loki
    namespace: monitoring
    valuesFile: loki-values.yaml   # Trỏ tới file values.yaml của Loki
    
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 0.10.0               # Điền version chart bạn muốn dùng
    releaseName: alloy
    namespace: monitoring
    valuesFile: alloy-values.yaml  # Trỏ tới file values.yaml của Alloy