# 1. Khai báo Secret lưu Credentials bảo mật
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "admin@123"
  POSTGRES_PASSWORD: "admin@123"
---
# 2. Khai báo PersistentVolumeClaim (PVC) để lưu trữ data không bị mất khi Pod restart
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi # Dung lượng ổ cứng muốn cấp phát cho Postgres
---
# 3. Khai báo Deployment chạy Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:trixie
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # Mount chuẩn cho Postgres
          # Chuyển đổi healthcheck từ Docker Compose sang Liveness/Readiness Probe
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# 4. Khai báo Service để các App khác trong cluster giao tiếp với Postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP # Dùng NodePort nếu muốn expose ra ngoài IP máy thật để debug
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432