apiVersion: v1
kind: Secret
metadata:
  name: backend-api-secret
type: Opaque
stringData: 
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "postgres"
  DATABASE_USER: "admin@123"
  DATABASE_PASSWORD: "admin@123"