services:
  JenkinsAgent_1:
    image: ssh-agent
    container_name: JenkinsAgent_1
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAPgAt9fhXzbegtlmv1GaU5Gci4Su+5DGwGDdSop6bDy ubuntu@ip-172-31-78-190
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
  JenkinsAgent_2:
    image: ssh-agent
    container_name: JenkinsAgent_2
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAPgAt9fhXzbegtlmv1GaU5Gci4Su+5DGwGDdSop6bDy ubuntu@ip-172-31-78-190
    ports:
      - "3333:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
  JenkinsAgent_3:
    image: ssh-agent
    container_name: JenkinsAgent_3
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAPgAt9fhXzbegtlmv1GaU5Gci4Su+5DGwGDdSop6bDy ubuntu@ip-172-31-78-190
    ports:
      - "4444:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

networks:
  jenkins:
    external: true