pipeline {
    agent {
        label 'be'
    }
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'f50ff99b-330f-4bfb-8ad5-5953526e33b4', url: 'https://github.com/Hungnd562k/devops-bootcamp-todolist-backend-api.git', branch: 'master'
            }
        }
        stage('Build') {
            steps {
                sh '''
                    docker run --rm \
                        -v "$(pwd)":/app \
                        -w /app \
                        node:18-alpine \
                        sh -c "node -v && npm install && npm run build"
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }
        stage('Quality gate') {
            steps {
                echo 'Quality gate'
            }
        }
    }
}